### ISSUE TITLE
loading extensions

### ISSUE THREAD

**Issue by ghennequin** [mmottl/sqlite3-ocaml#22]
Hi Markus, I'm having issues with extensions:

This fails:
```ocaml
let () = assert (Sqlite3.enable_load_extension db true)
```

This returns an `Error`:
```ocaml
let _ = Sqlite3.exec db "SELECT load_extension(\"sqlstat.so\")"
```
I have never had any issue with loading extensions in the `sqlite3` interpreter (i.e. the `SELECT load_extension(...)` statement above works fine).

I went back to the build dir in `.opam`, ran the configure script again, and got
```
Enable loadable extensions: .......................... true
```

Also,
```sh
strings /usr/lib/i386-linux-gnu/libsqlite3.so.0 | grep OMIT
```
gives only `OMIT_LOOKASIDE`.

Any ideas? Thanks!

**Comment by ghennequin** [comment]
PS: I have `libsqlite3 -- v3.16.2-4`

**Comment by mmottl** [comment]
It seems there was a bug in the return value of `enable_load_extension`: the result was just the opposite of what the documentation says.  Funny that nobody has checked for this so far.  If load extensions were not supported or enabled at all, the call would fail with an exception telling you so.  This means that your call probably worked just fine, but returned the wrong result.

I'm not sure what the problem is loading your `sqlstat.so` extension.  That may be an entirely different problem.  It may help in such cases to test loading the extension in pure C-code first to make sure the installed library works as expected.  If this works, it should be easy to track down any potential problem with the OCaml bindings.

I'll make a quick release fixing the return value problem.
